name: Numbers API App Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: lts
      - run: npm ci
      - run: npm run test.unit
      - run: npm run build
