name: Numbers API App Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Specify Node.js version
      - run: npm ci
      - run: npm run test.unit
      - run: npm run build
